dist: bionic

language: node_js

node_js:
  - '10'
  - '12'

cache:
  yarn: true
  directories:
    - node_modules/
    - packages/*/node_modules

addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.prosody.im/debian bionic main'
        key_url: 'https://prosody.im/files/prosody-debian-packages.key'
    packages:
      - prosody
      - lua-bitop # websocket
      - lua-sec # tls

before_script:
  - sudo service prosody stop

script:
  - make test-ci

after_failure:
  - cat server/prosody.err
