sudo: required
dist: trusty

language: node_js

node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y prosody # luarocks
  - sudo service prosody stop
  # - sudo luarocks install luabitop
  - sudo cp test/resources/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
  - sudo cp test/resources/mod_websocket.lua /usr/lib/prosody/modules/

script:
  - npm run test

  - nohup python2 -m SimpleHTTPServer &
  - sudo service prosody restart
  - npm run test:browser
  - sudo service prosody stop

  - npm run integration

after_script: npm run coveralls
