sudo: required

dist: trusty

language: node_js

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

cache:
  directories:
  - node_modules/
  - packages/*/node_modules

addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.prosody.im/debian trusty main'
      key_url: 'https://prosody.im/files/prosody-debian-packages.key'
    packages:
    - prosody-0.10
    - lua-bitop # websocket
    - lua-sec # tls
  hosts:
    - component.localhost

before_install:
  - sudo service prosody stop
  - sudo cp test/resources/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
  - sudo cp test/resources/localhost.crt /var/lib/prosody/
  - sudo cp test/resources/localhost.key /var/lib/prosody/

script:
  - npm run test

  - sudo prosodyctl start
  - sudo prosodyctl register node-xmpp localhost foobar
  - npm run ava:integration
